apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - radarr
  - sonarr
  - lidarr
  - prowlarr
  - qbittorrent
  - qbitwebui
  - sabnzbd
  - audiobookshelf
  - pinchflat
  - plex
  - tautulli
  - seerr
  - kometa
  - jellyfin
