apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbitwebui-credentials
  namespace: media
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: encryption-key
      remoteRef:
        key: qbitwebui/encryption-key
