---
services:
  # NOTE: visit https://<server-ip>:32400/web to setup new server
  plex:
    image: plexinc/pms-docker:1.43.2.10687-563d026ea@sha256:c37106c57fed7a6624f5dee5a3ce460ff011f09a2aa7f4ee9e8dbbd08ae1b87e
    container_name: plex
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex-data:/config
      - plex-transcode:/transcode
      - type: bind
        source: /mnt/data/media
        target: /data/media
        bind:
          propagation: rslave
      - type: bind
        source: /mnt/music
        target: /data/music
        bind:
          propagation: rslave
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.local.elmurphy.com`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
    restart: unless-stopped

  tautulli:
    image: ghcr.io/linuxserver/tautulli:v2.17.1-ls232@sha256:8e1a0d8104422f646c3e89d9b261b0507dc664bd6764baaea0ff0a5718f83b94
    container_name: tautulli
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - FOWNER
      - KILL
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - tautulli-data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.local.elmurphy.com`)
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8
    container_name: seerr
    init: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - seerr-data:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.seerr.rule=Host(`seerr.local.elmurphy.com`)
      - traefik.http.routers.seerr.tls=true
      - traefik.http.services.seerr.loadbalancer.server.port=5055
    restart: unless-stopped

  # Manually setup initial config
  # Reference: https://kometa.wiki/en/latest/kometa/install/walkthroughs/docker/#setting-up-the-initial-config-file
  kometa:
    image: kometateam/kometa:v2.3.1@sha256:683c04827ef3fecf1cc5cb178f75f91f968aef6c6d89d34bc9c70966fd1d7259
    container_name: kometa
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - proxy
    volumes:
      - kometa-data:/config:rw
    restart: unless-stopped

volumes:
  plex-data:
    name: plex-data
  plex-transcode:
    name: plex-transcode
  tautulli-data:
    name: tautulli-data
  seerr-data:
    name: seerr-data
  kometa-data:
    name: kometa-data

networks:
  proxy:
    external: true
