---
- name: configure users
  ansible.builtin.include_tasks:
    file: users.yaml

- name: harden ssh
  ansible.builtin.include_tasks:
    file: ssh.yaml

- name: configure journald retention
  ansible.builtin.include_tasks:
    file: journald.yaml

- name: pin cloud-init to its cached instance
  ansible.builtin.include_tasks:
    file: cloud-init.yaml
    apply:
      tags: cloud-init
  tags: cloud-init

- name: configure swap
  ansible.builtin.include_tasks:
    file: swap.yaml
    apply:
      tags: swap
  tags: swap
