---
- name: configure users
  ansible.builtin.include_tasks:
    file: users.yaml

- name: harden ssh
  ansible.builtin.include_tasks:
    file: ssh.yaml

- name: configure journald retention
  ansible.builtin.include_tasks:
    file: journald.yaml

- name: configure swap
  ansible.builtin.include_tasks:
    file: swap.yaml
    apply:
      tags: swap
  tags: swap
