---
- name: disable root login
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*PermitRootLogin\\s+.*$"
    line: "PermitRootLogin no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"

- name: disable password authentication
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*PasswordAuthentication\\s+.*$"
    line: "PasswordAuthentication no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"

- name: disable any keyboard interactive authentication
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*KbdInteractiveAuthentication\\s+.*$"
    line: "KbdInteractiveAuthentication no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"

- name: disable x11 forwarding
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*X11Forwarding\\s+.*$"
    line: "X11Forwarding no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"

- name: disable ssh-agent forwarding
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*AllowAgentForwarding\\s+.*$"
    line: "AllowAgentForwarding no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"

- name: disable unix-domain socket forwarding
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*AllowStreamLocalForwarding\\s+.*$"
    line: "AllowStreamLocalForwarding no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"

- name: set authentication methods to publickey
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^\\s*#?\\s*AuthenticationMethods\\s+.*$"
    line: "AuthenticationMethods publickey"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart sshd service"
