---
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:1.28.1-ls302@sha256:4cf45b2c316286f446a3eb2d7034a300c8488147bb6deb434f196167facc46c2
    container_name: freshrss
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - freshrss-data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`freshrss.local.elmurphy.com`)
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
    restart: unless-stopped

volumes:
  freshrss-data:
    name: freshrss-data

networks:
  proxy:
    external: true
