---
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:1.28.1-ls301@sha256:e717cfb455202f38a61d50f5df21b421c11fabca3f288ee121cc8470323dddd3
    container_name: freshrss
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - freshrss-data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`freshrss.local.elmurphy.com`)
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
    restart: unless-stopped

volumes:
  freshrss-data:
    name: freshrss-data

networks:
  proxy:
    external: true
