---
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:1.29.1-ls306@sha256:5292f1d623f621d65c8ecd0034b7cf637531f0ad6008b08affd6a73e32b902ea
    container_name: freshrss
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - freshrss-data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`freshrss.local.elmurphy.com`)
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
    restart: unless-stopped

volumes:
  freshrss-data:
    name: freshrss-data

networks:
  proxy:
    external: true
