apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
