apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        # supplementalGroups: [992] # render group
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
          ports:
            - containerPort: 8096
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: jellyfin-data
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
            - name: jellyfin-transcode
              mountPath: /transcode
            - name: media
              mountPath: /data/media
              subPath: media
          resources:
            requests:
              cpu: 100m
            #   gpu.intel.com/i915: 1
            # limits:
            #   memory: 4Gi
            #   gpu.intel.com/i915: 1
      volumes:
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data-pvc
        - name: jellyfin-cache
          emptyDir:
            sizeLimit: 2Gi
        - name: jellyfin-transcode
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
        - name: media
          nfs:
            server: 10.77.1.101
            path: /mnt/slow/media
            readOnly: true
