apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owncloud-credentials
  namespace: tools
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: db-password
      remoteRef:
        key: owncloud/db-password
    - secretKey: admin-username
      remoteRef:
        key: owncloud/admin-username
    - secretKey: admin-password
      remoteRef:
        key: owncloud/admin-password
