apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: immich
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: db-password
      remoteRef:
        key: immich/db-password
    - secretKey: db-username
      remoteRef:
        key: immich/db-username
    - secretKey: db-name
      remoteRef:
        key: immich/db-name
