apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-credentials
  namespace: tools
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: db-password
      remoteRef:
        key: wallabag/db-password
