---
services:
  beszel:
    image: henrygd/beszel:0.18.6@sha256:3135185161e072a5058f7c05b247345072bd9f3e23a4a9cd8c879880b085bc41
    container_name: beszel
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - DISABLE_PASSWORD_AUTH=true # use pocket-id
    volumes:
      - beszel-data:/beszel_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.local.elmurphy.com`)
      - traefik.http.routers.beszel.tls=true
      - traefik.http.services.beszel.loadbalancer.server.port=8090
    restart: unless-stopped

volumes:
  beszel-data:
    name: beszel-data

networks:
  proxy:
    external: true
