apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-credentials
  namespace: auth
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: encryption-key
      remoteRef:
        key: pocket-id/encryption-key
    - secretKey: maxmind-license-key
      remoteRef:
        key: pocket-id/maxmind-license-key
