apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
