---
services:
  couchdb:
    image: couchdb:3.5.1@sha256:d55f35ffc020ca4c615fccfddd4f893d11f957593b12b33fce5e7b0840366ccd
    container_name: couchdb
    security_opt:
      - no-new-privileges:true
    user: 5984:5984
    networks:
      - proxy
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb-data:/opt/couchdb/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.couchdb.rule=Host(`couchdb.local.elmurphy.com`)
      - traefik.http.routers.couchdb.tls=true
      - traefik.http.services.couchdb.loadbalancer.server.port=5984
      - traefik.http.routers.couchdb.middlewares=obsidiancors
      - traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE
      - traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer
      - traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost
      - traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600
      - traefik.http.middlewares.obsidiancors.headers.addvaryheader=true
      - traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true
    restart: unless-stopped

volumes:
  couchdb-data:
    name: couchdb-data

networks:
  proxy:
    external: true
