---
- hosts: docker
  become: true
  vars_files:
    - "group_vars/secrets.yaml"
  roles:
    - common
    - firewall
    - media
    - docker

- hosts: ai-dev
  become: true
  remote_user: michael
  roles:
    - common
    - ai-dev
