---
services:
  komga:
    image: gotson/komga:1.24.2@sha256:c6de009c5bfb3473e6e35b6257c19a8bb8a4ea6302307257126c9d491887d0e4
    container_name: komga
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - komga-data:/config:rw
      - /mnt/data/media/manga:/data:rw
      - /etc/timezone:/etc/timezone:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.komga.rule=Host(`komga.local.elmurphy.com`)
      - traefik.http.routers.komga.tls=true
      - traefik.http.services.komga.loadbalancer.server.port=25600
    restart: unless-stopped

volumes:
  komga-data:
    name: komga-data

networks:
  proxy:
    external: true
