apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-credentials
  namespace: tools
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        db-password: "{{ .dbPassword }}"
        admin-username: "{{ .adminUsername }}"
        admin-password: "{{ .adminPassword }}"
        database-url: postgres://miniflux:{{ .dbPassword }}@miniflux-db/miniflux?sslmode=disable
  data:
    - secretKey: dbPassword
      remoteRef:
        key: miniflux/db-password
    - secretKey: adminUsername
      remoteRef:
        key: miniflux/admin-username
    - secretKey: adminPassword
      remoteRef:
        key: miniflux/admin-password
