apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-db
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
