---
- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Clone neovim config
  ansible.builtin.git:
    repo: https://github.com/mich-murphy/neovim.git
    dest: "/home/{{ username }}/.config/nvim"
    version: HEAD
    update: false
  become: true
  become_user: "{{ username }}"
