---
- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Ensure the Neovim site plugin directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.local/share/nvim/site/plugin"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Configure Neovim to copy through OSC 52
  ansible.builtin.copy:
    src: osc52.lua
    dest: "/home/{{ username }}/.local/share/nvim/site/plugin/osc52.lua"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
