---
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:v2025.6.6@sha256:4e975edf58f0861a5cbfe8fc6aac4851ff5a02dfc3f05ffeea4982e3084a5a4a
    container_name: pinchflat
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - proxy
    environment:
      - TZ=${TZ}
    volumes:
      - type: bind
        source: /mnt/data/media/youtube
        target: /downloads
        bind:
          propagation: rslave
      - pinchflat-data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.pinchflat.rule=Host(`pinchflat.local.elmurphy.com`)
      - traefik.http.routers.pinchflat.tls=true
      - traefik.http.services.pinchflat.loadbalancer.server.port=8945
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8945/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  pinchflat-data:
    name: pinchflat-data

networks:
  proxy:
    external: true
