name: Actions Runner Controller Test
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-actions-runner:
    runs-on: home-infra-runner
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
