name: GitHub Runner Test
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-github-runner:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GitHub-hosted runner is available."
