apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-credentials
  namespace: media
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: claim
      remoteRef:
        key: plex/claim
